// Code generated by Kitex v0.4.4. DO NOT EDIT.

package messageservice

import (
	"context"
	message "douyin/kitex_gen/message"
	client "github.com/cloudwego/kitex/client"
	kitex "github.com/cloudwego/kitex/pkg/serviceinfo"
)

func serviceInfo() *kitex.ServiceInfo {
	return messageServiceServiceInfo
}

var messageServiceServiceInfo = NewServiceInfo()

func NewServiceInfo() *kitex.ServiceInfo {
	serviceName := "MessageService"
	handlerType := (*message.MessageService)(nil)
	methods := map[string]kitex.MethodInfo{
		"MessageChat":           kitex.NewMethodInfo(messageChatHandler, newMessageServiceMessageChatArgs, newMessageServiceMessageChatResult, false),
		"RelationActionMessage": kitex.NewMethodInfo(relationActionMessageHandler, newMessageServiceRelationActionMessageArgs, newMessageServiceRelationActionMessageResult, false),
	}
	extra := map[string]interface{}{
		"PackageName": "message",
	}
	svcInfo := &kitex.ServiceInfo{
		ServiceName:     serviceName,
		HandlerType:     handlerType,
		Methods:         methods,
		PayloadCodec:    kitex.Thrift,
		KiteXGenVersion: "v0.4.4",
		Extra:           extra,
	}
	return svcInfo
}

func messageChatHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*message.MessageServiceMessageChatArgs)
	realResult := result.(*message.MessageServiceMessageChatResult)
	success, err := handler.(message.MessageService).MessageChat(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newMessageServiceMessageChatArgs() interface{} {
	return message.NewMessageServiceMessageChatArgs()
}

func newMessageServiceMessageChatResult() interface{} {
	return message.NewMessageServiceMessageChatResult()
}

func relationActionMessageHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*message.MessageServiceRelationActionMessageArgs)
	realResult := result.(*message.MessageServiceRelationActionMessageResult)
	success, err := handler.(message.MessageService).RelationActionMessage(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newMessageServiceRelationActionMessageArgs() interface{} {
	return message.NewMessageServiceRelationActionMessageArgs()
}

func newMessageServiceRelationActionMessageResult() interface{} {
	return message.NewMessageServiceRelationActionMessageResult()
}

type kClient struct {
	c client.Client
}

func newServiceClient(c client.Client) *kClient {
	return &kClient{
		c: c,
	}
}

func (p *kClient) MessageChat(ctx context.Context, req *message.MessageChatRequest) (r *message.MessageChatResponse, err error) {
	var _args message.MessageServiceMessageChatArgs
	_args.Req = req
	var _result message.MessageServiceMessageChatResult
	if err = p.c.Call(ctx, "MessageChat", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) RelationActionMessage(ctx context.Context, req *message.RelationActionMessageRequest) (r *message.RelationActionMessageResponse, err error) {
	var _args message.MessageServiceRelationActionMessageArgs
	_args.Req = req
	var _result message.MessageServiceRelationActionMessageResult
	if err = p.c.Call(ctx, "RelationActionMessage", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}
