// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/gorm"
)

const TableNameFollow = "follows"

// Follow mapped from table <follows>
type Follow struct {
	ID         int64          `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	CreatedAt  time.Time      `gorm:"column:created_at" json:"created_at"`
	UpdatedAt  time.Time      `gorm:"column:updated_at" json:"updated_at"`
	DeletedAt  gorm.DeletedAt `gorm:"column:deleted_at" json:"deleted_at"`
	UserID     int64          `gorm:"column:user_id" json:"user_id"`
	ToUserID   int64          `gorm:"column:to_user_id" json:"to_user_id"`
	ActionType int32          `gorm:"column:action_type" json:"action_type"`
}

// TableName Follow's table name
func (*Follow) TableName() string {
	return TableNameFollow
}
