// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/gorm"
)

const TableNameMessage = "messages"

// Message mapped from table <messages>
type Message struct {
	ID          int64          `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	CreatedAt   time.Time      `gorm:"column:created_at" json:"created_at"`
	UpdatedAt   time.Time      `gorm:"column:updated_at" json:"updated_at"`
	DeletedAt   gorm.DeletedAt `gorm:"column:deleted_at" json:"deleted_at"`
	Content     string         `gorm:"column:content" json:"content"`
	FromUserID  int64          `gorm:"column:from_user_id" json:"from_user_id"`
	ToUserID    int64          `gorm:"column:to_user_id" json:"to_user_id"`
	MessageTime time.Time      `gorm:"column:message_time" json:"message_time"`
}

// TableName Message's table name
func (*Message) TableName() string {
	return TableNameMessage
}
