// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/gorm"
)

const TableNameVideo = "videos"

// Video mapped from table <videos>
type Video struct {
	ID            int64          `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	CreatedAt     time.Time      `gorm:"column:created_at" json:"created_at"`
	UpdatedAt     time.Time      `gorm:"column:updated_at" json:"updated_at"`
	DeletedAt     gorm.DeletedAt `gorm:"column:deleted_at" json:"deleted_at"`
	AuthorID      int64          `gorm:"column:author_id" json:"author_id"`
	PlayURL       string         `gorm:"column:play_url" json:"play_url"`
	CoverURL      string         `gorm:"column:cover_url" json:"cover_url"`
	FavoriteCount int64          `gorm:"column:favorite_count" json:"favorite_count"`
	CommentCount  int64          `gorm:"column:comment_count" json:"comment_count"`
	Title         string         `gorm:"column:title" json:"title"`
}

// TableName Video's table name
func (*Video) TableName() string {
	return TableNameVideo
}
